### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by dluc** [Azure/device-simulation-dotnet#224]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Occurring when the VM CPU is under stress:

```
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.566][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":1,"deviceId":"chiller-01.21599","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.568][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.570][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.571][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":1,"deviceId":"chiller-01.14827","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.572][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.573][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":2,"deviceId":"chiller-01.995","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.575][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery timed out, {"Protocol":"AMQP","ExceptionMessage":"Operation timeout expired.","Exception":"System.TimeoutException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.575][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery timed out, {"Protocol":"AMQP","ExceptionMessage":"Operation timeout expired.","Exception":"System.TimeoutException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.575][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.576][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":4,"deviceId":"chiller-01.1049","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.578][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.578][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.580][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send timeout error, {"timeSpentMsecs":20003,"deviceId":"chiller-01.12129","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendTimeoutException","ExceptionMessage":"Message delivery timed out with Operation timeout expired.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 193\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.TimeoutException","ExceptionMessage":"Operation timeout expired.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.580][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send timeout error, {"timeSpentMsecs":20003,"deviceId":"chiller-01.4687","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendTimeoutException","ExceptionMessage":"Message delivery timed out with Operation timeout expired.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 193\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.TimeoutException","ExceptionMessage":"Operation timeout expired.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.581][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":3,"deviceId":"chiller-01.1741","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.582][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":4,"deviceId":"chiller-01.19645","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.582][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery timed out, {"Protocol":"AMQP","ExceptionMessage":"Operation timeout expired.","Exception":"System.TimeoutException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.582][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery timed out, {"Protocol":"AMQP","ExceptionMessage":"Operation timeout expired.","Exception":"System.TimeoutException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.583][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.583][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.584][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][SendTelemetry:SendTelemetryMessage] Telemetry send unknown error, {"timeSpentMsecs":3,"deviceId":"chiller-01.22198","exception":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.TelemetrySendException","ExceptionMessage":"Message delivery failed with Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 234\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendMessageAsync>d__18.MoveNext() in /build/Services/DeviceClient.cs:line 131","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.ObjectDisposedException","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__20.MoveNext() in /build/Services/DeviceClient.cs:line 177","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.584][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.584][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
devicesimulation-svc_1 | [ERROR][2018-07-02 00:12:16.584][WebService.59503a1a-1e1d-4375-80ae-4039fc77a845][DeviceClient:SendRawMessageAsync] Message delivery failed, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.\nObject name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}
```

**Comment by imabusyman** [comment]
I am getting the same thing when calling EventHubClient.SendAsysnc


Test method EventHubTests.EventHubUnitTest.TestSendAsync threw exception: 
System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FaultTolerantAmqpObject`1'.
    at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<CreateLinkAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.<OnCreateAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.EventHubClient.<SendAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Com.TheToroCo.Repository.Azure.EventService.EventHub.Context.Model.ToroEventHubProvider.<SendAsync>d__7`1.MoveNext() in D:\src\Azure\DataProvider\DataProvider_Azure_EventHub\Com.TheToroCo.Repository.Azure.EventHub.Context\Model\ToroEventHubProvider.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EventHubTests.EventHubUnitTest.<>c__DisplayClass2_0.<<TestSendAsync>b__1>d.MoveNext() in D:\src\Azure\DataProvider\DataProvider_Azure_EventHub\EventHubTests\EventHubUnitTest.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Com.TheToroCo.Common.Portable.Core.Extensions.ObjectExtensions.<ForEachCoreAsync>d__6`1.MoveNext()
 --- End of inner exception stack trace ---
    at Com.TheToroCo.Common.Portable.Core.Extensions.ObjectExtensions.<ForEachCoreAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EventHubTests.EventHubUnitTest.<TestSendAsync>d__2.MoveNext() in D:\src\Azure\DataProvider\DataProvider_Azure_EventHub\EventHubTests\EventHubUnitTest.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
