### ISSUE TITLE
Environment variable not found: PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING

### ISSUE THREAD

**Issue by thovoll** [Azure/device-simulation-dotnet#260]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
It seems the code is looking for CosmosDB settings. I thought all it needs is the Storage Adapter settings?

{Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.InvalidConfigurationException: Environment variables not found: , PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Runtime.ConfigData.ProcessMandatoryPlaceholders(String& value) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\Services\Runtime\ConfigData.cs:line 170
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Runtime.ConfigData.ReplaceEnvironmentVariables(String& value, String defaultValue) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\Services\Runtime\ConfigData.cs:line 133
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Runtime.ConfigData.GetStringInternal(String key, String defaultValue) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\Services\Runtime\ConfigData.cs:line 122
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Runtime.ConfigData.GetString(String key, String defaultValue) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\Services\Runtime\ConfigData.cs:line 37
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.Runtime.Config.GetStorageConfig(IConfigData configData, String prefix) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\Runtime\Config.cs:line 236
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.Runtime.Config.GetServicesConfig(IConfigData configData) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\Runtime\Config.cs:line 214
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.Runtime.Config..ctor(IConfigData configData) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\Runtime\Config.cs:line 137
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.DependencyResolution.GetConfig(IConfigurationRoot& configuration) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\DependencyResolution.cs:line 89
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.DependencyResolution.GetConfig() in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\DependencyResolution.cs:line 48
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.Program.Main(String[] args) in c:\Code\Github\thovoll\Forks\Azure\device-simulation-dotnet\WebService\Program.cs:line 15}

...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by dluc** [comment]
this should have been fixed, @hathind-ms could you verify?

**Comment by hathind-ms** [comment]
@thovoll - are you using latest from master? We have introduced a new Storage Library, and simulation service reads simulation definitions directly from storage now. So this property is required.

**Comment by thovoll** [comment]
Thanks @hathind-ms. The thing I didn't know is that you're migrating away from storage adapter and towards using CosmosDB directly, and that the migration is only partially complete. Now that I understand this, I agree with @dluc - it's a doc issue.

**Comment by hathind-ms** [comment]
I will review the documentation and update it.

**Comment by thovoll** [comment]
Thanks @hathind-ms. Also, /scripts/env-vars* needs to be updated.
