### ISSUE TITLE
Unable to upload custom device JSON

### ISSUE THREAD

**Issue by hoekj** [Azure/device-simulation-dotnet#348]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Unable to create a new device definition in advanced mode. After selecting the JSON file, the app crashes and a whitescreen is displayed. In de console log the following errors appears:

react-dom.production.min.js:3833 Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Invalid%20attempt%20to%20spread%20non-iterable%20instance&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1111720
    at s (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1111823)
    at Fi (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1161411)
    at d (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1163049)
    at m (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1164157)
    at https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1166138
    at eo (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1167392)
    at ho (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1175424)
    at Vo (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1189979)
    at Uo (https://*****-t4x4z.azurewebsites.net/static/js/1.29a0246d.chunk.js:1:1190356)

# Steps to reproduce 

1. Open devicemodels pane
2. Click "Add Device Model"
3. Select Advanced
4. Upload JSON (From https://github.com/Azure/device-simulation-dotnet/wiki/Device-Models)
After uploading, the app crashes

# Expected behavior 
A new model is displayed, or an error message is displayed if the JSON is incorrect

# Current behavior 
White screen

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* GitHub branch: 
Deployed from https://www.azureiotsolutions.com/Accelerators#description/device-simulation

**Comment by troyhopwood** [comment]
There were some bugs in the JSON that caused the UX to misbehave upon validation. I have updated the wiki so the JSON file is correct.
